site_name: å…¨æ°‘ç˜‹AIç³»åˆ— [å¤§èªè¨€æ¨¡å‹æ‡‰ç”¨èˆ‡å¯¦æˆ°]
site_author: 10ç¨‹å¼ä¸­
site_url: https://andy6804tw.github.io/crazyai-llm/
extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/analytics.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
theme:
  name: material
  language: 'zh-TW'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'blue'
    accent: 'light blue'
repo_url: https://github.com/andy6804tw/crazyai-llm
# use_directory_urls: false
edit_uri: ""
# Copyright
copyright: 'Copyright Â© 2024 - 2025 10ç¨‹å¼ä¸­'
nav:
  - 'ç›®éŒ„': './tags.md'
  - 'ğŸ“šæå®æ¯…ç”Ÿæˆå¼AIå°è«–(2024)':
    - '1.ç”Ÿæˆå¼AIæ˜¯ä»€éº¼': 'intro-generative-ai/1.what-is-generative-ai.md.md'
    - '2.ä»Šæ—¥çš„ç”Ÿæˆå¼äººå·¥æ™ºæ…§å²å®³åœ¨å“ªè£¡': 'intro-generative-ai/2.why-generative-ai-is-powerful.md'
    - '3.è¨“ç·´ä¸äº†äººå·¥æ™ºæ…§?ä½ å¯ä»¥è¨“ç·´ä½ è‡ªå·±(ä¸Š)': 'intro-generative-ai/3.cant-train-ai-train-yourself-part1.md'
    - '4.è¨“ç·´ä¸äº†äººå·¥æ™ºæ…§?ä½ å¯ä»¥è¨“ç·´ä½ è‡ªå·±(ä¸­)': 'intro-generative-ai/4.cant-train-ai-train-yourself-part2.md'
    - '5.è¨“ç·´ä¸äº†äººå·¥æ™ºæ…§?ä½ å¯ä»¥è¨“ç·´ä½ è‡ªå·±(ä¸‹)': 'intro-generative-ai/5.cant-train-ai-train-yourself-part3.md'
    - '6.å¤§å‹èªè¨€æ¨¡å‹ä¿®ç·´å²(ç¬¬ä¸€éšæ®µ)': 'intro-generative-ai/6.llm-history-phase1.md'
    - '7.å¤§å‹èªè¨€æ¨¡å‹ä¿®ç·´å²(ç¬¬äºŒéšæ®µ)': 'intro-generative-ai/7.llm-history-phase2.md'
    - '8.å¤§å‹èªè¨€æ¨¡å‹ä¿®ç·´å²(ç¬¬ä¸‰éšæ®µ)': 'intro-generative-ai/8.llm-history-phase3.md'
    - '9.ä»¥å¤§å‹èªè¨€æ¨¡å‹æ‰“é€ çš„ AI Agent': 'intro-generative-ai/9.llm-ai-agent.md'
  - 'ğŸ“š5-Day Gen AI Intensive':
    - 'èª²ç¨‹ä»‹ç´¹': 'google-genai-course/2025-03-30-course-intro.md'
    - '[Day 1]å¤§å‹èªè¨€æ¨¡å‹åŸºç¤èˆ‡æç¤ºå·¥ç¨‹': 'google-genai-course/2025-03-31-day1.md'
    - '[Day 2]Embeddings èˆ‡å‘é‡è³‡æ–™åº«': 'google-genai-course/2025-04-01-day2.md'
    - '[Day 3]ç”Ÿæˆå¼ AI ä»£ç†äºº': 'google-genai-course/2025-04-02-day3.md'
    - '[Day 4]ç‰¹å®šé ˜åŸŸå¤§å‹èªè¨€æ¨¡å‹': 'google-genai-course/2025-04-03-day4.md'
    - '[Day 5]ç”Ÿæˆå¼ AI çš„ MLOps': 'google-genai-course/2025-04-04-day5.md'

  - 'ğŸ’»LLMå¯¦æˆ°æ‡‰ç”¨':
    - 'Ollamaä½¿ç”¨æ•™å­¸': 'llm-practical/Ollamaä½¿ç”¨æ•™å­¸.md'
    - 'Ollama APIæ•´åˆOpenAI': 'llm-practical/Ollama APIæ•´åˆOpenAI.md'
    - 'ç”¨Colabéƒ¨ç½²Ollamaæœå‹™': 'llm-practical/ä½¿ç”¨Colabéƒ¨ç½²Ollamaæœå‹™.md'
    - 'ä½¿ç”¨Streamlitèˆ‡Ollamaå»ºç«‹èŠå¤©ä»‹é¢': 'llm-practical/ä½¿ç”¨Streamlitèˆ‡Ollamaå»ºç«‹èŠå¤©ä»‹é¢.md'
    - 'OpenAI Agents SDKå¤šä»£ç†äººå·¥ä½œæµç¨‹æ•™å­¸': 'llm-practical/openai-agents-sdk-tutorial.md'
    - 'æ·±å…¥ç†è§£ MCP æ­é…ç°¡æ˜“å¯¦ä½œ': 'llm-practical/mcp-tutorial.md'
    - 'Qdrant åœ–ç‰‡å‘é‡åº«æ•™å­¸': 'llm-practical/qdrant-image-similarity-search.md'

  - 'ğŸ¤–å…è²» LLM API ä¸²æ¥è³‡æº':
    - 'GitHub Models å…è²»è©¦ç©': 'free-llm-api-integration-resources/github-models-tutorial.md'
    - 'Groq å…è²»é«”é©— Llama API': 'free-llm-api-integration-resources/groq-tutorial.md'

  - 'ğŸ› ï¸ç†±é–€AIå·¥å…·ä½¿ç”¨æ•™å­¸':
    - 'ğŸ–¼ï¸Raphaelå…è²»AIåœ–åƒç”Ÿæˆå·¥å…·': 'aigc-tools/AIåœ–ç‰‡ç”Ÿæˆ-Raphaelå…è²»AIåœ–åƒç”Ÿæˆå·¥å…·.md'
    - 'ğŸµSunoä½œæ›²åŠéŸ³æ¨‚ç”Ÿæˆå™¨': 'aigc-tools/AIç”ŸæˆéŸ³æ¨‚-ç”¨Suno.aiè¼•é¬†æ‰“é€ å±¬æ–¼ä½ çš„AIéŸ³æ¨‚.md'
    - 'ğŸ“åˆ©ç”¨ Google NotebookLM æ‰“é€ é«˜æ•ˆå­¸ç¿’ç­†è¨˜': 'aigc-tools/åˆ©ç”¨ Google NotebookLM æ‰“é€ é«˜æ•ˆå­¸ç¿’ç­†è¨˜.md'

  - 'ç”¨Difyæ‰“é€ å°ˆå±¬AIåŠ©ç†':
    -  'å»ºç«‹ç¬¬ä¸€å€‹æ‡‰ç”¨': 'dify-tutorial/1.1ä»‹é¢ä»‹ç´¹.md'
    - 'ä½¿ç”¨ Dify æ‰“é€  AI å®¢æœçŸ¥è­˜åº«': 'dify-tutorial/knowledge-retrieval.md'
    - 'ä½¿ç”¨ Dify å·¥ä½œæµæ‰“é€  RAG AI å®¢æœç³»çµ±(åŸºç¤ç¯‡)': 'dify-tutorial/chatflow-rag-chatbot-tutorial-1.md'
    - 'ä½¿ç”¨ Dify å·¥ä½œæµæ‰“é€  RAG AI å®¢æœç³»çµ±(é€²éšç¯‡)': 'dify-tutorial/chatflow-rag-chatbot-tutorial-2.md'
    - 'Dify Agent æ•™å­¸': 'dify-tutorial/agent-tutorial.md'
    - 'Dify è‡ªè¨‚æ¨¡å‹æ•™å­¸': 'dify-tutorial/dify-custom-tools-workflow.md'

markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
  # katex math
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - tags:
      tags_file: tags.md
  - search
  - glightbox
